// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 对应 `books` 表
class Book {
  final String bookId;
  final String name;
  final String author;
  final String? kind;
  final String? coverUrl;
  final String? intro;
  final String? origin;
  final String bookType;
  final int wordCount;
  final String? latestChapterTitle;
  final String? tocUrl;
  final String? bookGroup;

  /// 添加时间，使用时间戳（秒）
  final PlatformInt64 addTime;
  final PlatformInt64? lastReadTime;
  final String? isbn;
  final String? publisher;
  final PlatformInt64? publishDate;
  final String status;

  const Book({
    required this.bookId,
    required this.name,
    required this.author,
    this.kind,
    this.coverUrl,
    this.intro,
    this.origin,
    required this.bookType,
    required this.wordCount,
    this.latestChapterTitle,
    this.tocUrl,
    this.bookGroup,
    required this.addTime,
    this.lastReadTime,
    this.isbn,
    this.publisher,
    this.publishDate,
    required this.status,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      name.hashCode ^
      author.hashCode ^
      kind.hashCode ^
      coverUrl.hashCode ^
      intro.hashCode ^
      origin.hashCode ^
      bookType.hashCode ^
      wordCount.hashCode ^
      latestChapterTitle.hashCode ^
      tocUrl.hashCode ^
      bookGroup.hashCode ^
      addTime.hashCode ^
      lastReadTime.hashCode ^
      isbn.hashCode ^
      publisher.hashCode ^
      publishDate.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Book &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          name == other.name &&
          author == other.author &&
          kind == other.kind &&
          coverUrl == other.coverUrl &&
          intro == other.intro &&
          origin == other.origin &&
          bookType == other.bookType &&
          wordCount == other.wordCount &&
          latestChapterTitle == other.latestChapterTitle &&
          tocUrl == other.tocUrl &&
          bookGroup == other.bookGroup &&
          addTime == other.addTime &&
          lastReadTime == other.lastReadTime &&
          isbn == other.isbn &&
          publisher == other.publisher &&
          publishDate == other.publishDate &&
          status == other.status;
}
