// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rules.dart';

class BookSource {
  final String bookSourceUrl;
  final String bookSourceName;
  final String? bookSourceGroup;
  final int bookSourceType;
  final String? bookUrlPattern;
  final int customOrder;
  final bool enabled;
  final bool enabledExplore;
  final String? jsLib;
  final bool enabledCookieJar;
  final String? concurrentRate;
  final String? header;
  final String? loginUrl;
  final String? loginUi;
  final String? loginCheckJs;
  final String? coverDecodeJs;
  final String? bookSourceComment;
  final String? variableComment;
  final String lastUpdateTime;
  final int respondTime;
  final int weight;
  final String? exploreUrl;
  final String? exploreScreen;
  final ExploreRule? ruleExplore;
  final String? searchUrl;
  final SearchRule? searchRule;
  final BookInfoRule? bookInfoRule;
  final TocRule? tocRule;
  final ContentRule? contentRule;
  final ReviewRule? reviewRule;

  const BookSource({
    required this.bookSourceUrl,
    required this.bookSourceName,
    this.bookSourceGroup,
    required this.bookSourceType,
    this.bookUrlPattern,
    required this.customOrder,
    required this.enabled,
    required this.enabledExplore,
    this.jsLib,
    required this.enabledCookieJar,
    this.concurrentRate,
    this.header,
    this.loginUrl,
    this.loginUi,
    this.loginCheckJs,
    this.coverDecodeJs,
    this.bookSourceComment,
    this.variableComment,
    required this.lastUpdateTime,
    required this.respondTime,
    required this.weight,
    this.exploreUrl,
    this.exploreScreen,
    this.ruleExplore,
    this.searchUrl,
    this.searchRule,
    this.bookInfoRule,
    this.tocRule,
    this.contentRule,
    this.reviewRule,
  });

  @override
  int get hashCode =>
      bookSourceUrl.hashCode ^
      bookSourceName.hashCode ^
      bookSourceGroup.hashCode ^
      bookSourceType.hashCode ^
      bookUrlPattern.hashCode ^
      customOrder.hashCode ^
      enabled.hashCode ^
      enabledExplore.hashCode ^
      jsLib.hashCode ^
      enabledCookieJar.hashCode ^
      concurrentRate.hashCode ^
      header.hashCode ^
      loginUrl.hashCode ^
      loginUi.hashCode ^
      loginCheckJs.hashCode ^
      coverDecodeJs.hashCode ^
      bookSourceComment.hashCode ^
      variableComment.hashCode ^
      lastUpdateTime.hashCode ^
      respondTime.hashCode ^
      weight.hashCode ^
      exploreUrl.hashCode ^
      exploreScreen.hashCode ^
      ruleExplore.hashCode ^
      searchUrl.hashCode ^
      searchRule.hashCode ^
      bookInfoRule.hashCode ^
      tocRule.hashCode ^
      contentRule.hashCode ^
      reviewRule.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSource &&
          runtimeType == other.runtimeType &&
          bookSourceUrl == other.bookSourceUrl &&
          bookSourceName == other.bookSourceName &&
          bookSourceGroup == other.bookSourceGroup &&
          bookSourceType == other.bookSourceType &&
          bookUrlPattern == other.bookUrlPattern &&
          customOrder == other.customOrder &&
          enabled == other.enabled &&
          enabledExplore == other.enabledExplore &&
          jsLib == other.jsLib &&
          enabledCookieJar == other.enabledCookieJar &&
          concurrentRate == other.concurrentRate &&
          header == other.header &&
          loginUrl == other.loginUrl &&
          loginUi == other.loginUi &&
          loginCheckJs == other.loginCheckJs &&
          coverDecodeJs == other.coverDecodeJs &&
          bookSourceComment == other.bookSourceComment &&
          variableComment == other.variableComment &&
          lastUpdateTime == other.lastUpdateTime &&
          respondTime == other.respondTime &&
          weight == other.weight &&
          exploreUrl == other.exploreUrl &&
          exploreScreen == other.exploreScreen &&
          ruleExplore == other.ruleExplore &&
          searchUrl == other.searchUrl &&
          searchRule == other.searchRule &&
          bookInfoRule == other.bookInfoRule &&
          tocRule == other.tocRule &&
          contentRule == other.contentRule &&
          reviewRule == other.reviewRule;
}
