// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ChapterContent {
  final String bookId;
  final String content;

  const ChapterContent({required this.bookId, required this.content});

  @override
  int get hashCode => bookId.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterContent &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          content == other.content;
}
