// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 对应 `chapters` 表
class Chapter {
  final int id;
  final String bookId;
  final String title;
  final String url;
  final int chapterIndex;
  final int wordCount;
  final bool isVip;

  const Chapter({
    required this.id,
    required this.bookId,
    required this.title,
    required this.url,
    required this.chapterIndex,
    required this.wordCount,
    required this.isVip,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      title.hashCode ^
      url.hashCode ^
      chapterIndex.hashCode ^
      wordCount.hashCode ^
      isVip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chapter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          title == other.title &&
          url == other.url &&
          chapterIndex == other.chapterIndex &&
          wordCount == other.wordCount &&
          isVip == other.isVip;
}
