// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 对应 `read_records` 表
class ReadRecord {
  final String bookId;
  final BigInt durChapterIndex;
  final BigInt durChapterPos;
  final BigInt lastChapterIndex;
  final BigInt lastChapterPos;
  final BigInt totalReadTime;

  /// 文档在索引优化中引用了 `last_read_time`，这里额外加一个字段以便扩展
  final PlatformInt64? lastReadTime;

  const ReadRecord({
    required this.bookId,
    required this.durChapterIndex,
    required this.durChapterPos,
    required this.lastChapterIndex,
    required this.lastChapterPos,
    required this.totalReadTime,
    this.lastReadTime,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      durChapterIndex.hashCode ^
      durChapterPos.hashCode ^
      lastChapterIndex.hashCode ^
      lastChapterPos.hashCode ^
      totalReadTime.hashCode ^
      lastReadTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadRecord &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          durChapterIndex == other.durChapterIndex &&
          durChapterPos == other.durChapterPos &&
          lastChapterIndex == other.lastChapterIndex &&
          lastChapterPos == other.lastChapterPos &&
          totalReadTime == other.totalReadTime &&
          lastReadTime == other.lastReadTime;
}
