// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 4.4.1 BookInfoRule (书籍信息规则)
class BookInfoRule {
  final String? init;
  final String? name;
  final String? author;
  final String? intro;
  final String? kind;
  final String? lastChapter;
  final String? updateTime;
  final String? coverUrl;
  final String? tocUrl;
  final String? wordCount;
  final bool? canReName;
  final String? downloadUrls;

  const BookInfoRule({
    this.init,
    this.name,
    this.author,
    this.intro,
    this.kind,
    this.lastChapter,
    this.updateTime,
    this.coverUrl,
    this.tocUrl,
    this.wordCount,
    this.canReName,
    this.downloadUrls,
  });

  @override
  int get hashCode =>
      init.hashCode ^
      name.hashCode ^
      author.hashCode ^
      intro.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      updateTime.hashCode ^
      coverUrl.hashCode ^
      tocUrl.hashCode ^
      wordCount.hashCode ^
      canReName.hashCode ^
      downloadUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfoRule &&
          runtimeType == other.runtimeType &&
          init == other.init &&
          name == other.name &&
          author == other.author &&
          intro == other.intro &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          updateTime == other.updateTime &&
          coverUrl == other.coverUrl &&
          tocUrl == other.tocUrl &&
          wordCount == other.wordCount &&
          canReName == other.canReName &&
          downloadUrls == other.downloadUrls;
}

/// 4.4.2 ContentRule (正文页规则)
class ContentRule {
  final String? init;
  final String? content;
  final String? nextContent;
  final String? prevContent;
  final String? refreshContent;
  final String? replaceRegex;
  final String? removeRegex;
  final String? cssSelector;
  final bool? isWebView;
  final String? js;
  final String? encode;

  const ContentRule({
    this.init,
    this.content,
    this.nextContent,
    this.prevContent,
    this.refreshContent,
    this.replaceRegex,
    this.removeRegex,
    this.cssSelector,
    this.isWebView,
    this.js,
    this.encode,
  });

  @override
  int get hashCode =>
      init.hashCode ^
      content.hashCode ^
      nextContent.hashCode ^
      prevContent.hashCode ^
      refreshContent.hashCode ^
      replaceRegex.hashCode ^
      removeRegex.hashCode ^
      cssSelector.hashCode ^
      isWebView.hashCode ^
      js.hashCode ^
      encode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentRule &&
          runtimeType == other.runtimeType &&
          init == other.init &&
          content == other.content &&
          nextContent == other.nextContent &&
          prevContent == other.prevContent &&
          refreshContent == other.refreshContent &&
          replaceRegex == other.replaceRegex &&
          removeRegex == other.removeRegex &&
          cssSelector == other.cssSelector &&
          isWebView == other.isWebView &&
          js == other.js &&
          encode == other.encode;
}

/// 4.4.6 ExploreRule (发现规则)
class ExploreRule {
  final String? init;
  final String? list;
  final String? name;
  final String? url;
  final String? cover;
  final String? author;
  final String? intro;
  final String? kind;
  final String? lastChapter;
  final PlatformInt64? updateTime;
  final String? wordCount;
  final String? nextPage;
  final String? sort;
  final String? filter;
  final String? search;
  final String? comment;
  final String? chapter;
  final String? content;

  const ExploreRule({
    this.init,
    this.list,
    this.name,
    this.url,
    this.cover,
    this.author,
    this.intro,
    this.kind,
    this.lastChapter,
    this.updateTime,
    this.wordCount,
    this.nextPage,
    this.sort,
    this.filter,
    this.search,
    this.comment,
    this.chapter,
    this.content,
  });

  @override
  int get hashCode =>
      init.hashCode ^
      list.hashCode ^
      name.hashCode ^
      url.hashCode ^
      cover.hashCode ^
      author.hashCode ^
      intro.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      updateTime.hashCode ^
      wordCount.hashCode ^
      nextPage.hashCode ^
      sort.hashCode ^
      filter.hashCode ^
      search.hashCode ^
      comment.hashCode ^
      chapter.hashCode ^
      content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExploreRule &&
          runtimeType == other.runtimeType &&
          init == other.init &&
          list == other.list &&
          name == other.name &&
          url == other.url &&
          cover == other.cover &&
          author == other.author &&
          intro == other.intro &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          updateTime == other.updateTime &&
          wordCount == other.wordCount &&
          nextPage == other.nextPage &&
          sort == other.sort &&
          filter == other.filter &&
          search == other.search &&
          comment == other.comment &&
          chapter == other.chapter &&
          content == other.content;
}

/// 4.4.5 ReviewRule (评论规则)
class ReviewRule {
  final String? init;
  final String? list;
  final String? name;
  final String? content;
  final PlatformInt64? time;
  final String? rating;
  final String? nextPage;

  const ReviewRule({
    this.init,
    this.list,
    this.name,
    this.content,
    this.time,
    this.rating,
    this.nextPage,
  });

  @override
  int get hashCode =>
      init.hashCode ^
      list.hashCode ^
      name.hashCode ^
      content.hashCode ^
      time.hashCode ^
      rating.hashCode ^
      nextPage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewRule &&
          runtimeType == other.runtimeType &&
          init == other.init &&
          list == other.list &&
          name == other.name &&
          content == other.content &&
          time == other.time &&
          rating == other.rating &&
          nextPage == other.nextPage;
}

/// 4.4.3 SearchRule (搜索规则)
class SearchRule {
  final String? init;
  final String? list;
  final String? name;
  final String? url;
  final String? cover;
  final String? author;
  final String? intro;
  final String? kind;
  final String? lastChapter;
  final String? updateTime;
  final String? wordCount;
  final String? nextPage;

  const SearchRule({
    this.init,
    this.list,
    this.name,
    this.url,
    this.cover,
    this.author,
    this.intro,
    this.kind,
    this.lastChapter,
    this.updateTime,
    this.wordCount,
    this.nextPage,
  });

  @override
  int get hashCode =>
      init.hashCode ^
      list.hashCode ^
      name.hashCode ^
      url.hashCode ^
      cover.hashCode ^
      author.hashCode ^
      intro.hashCode ^
      kind.hashCode ^
      lastChapter.hashCode ^
      updateTime.hashCode ^
      wordCount.hashCode ^
      nextPage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchRule &&
          runtimeType == other.runtimeType &&
          init == other.init &&
          list == other.list &&
          name == other.name &&
          url == other.url &&
          cover == other.cover &&
          author == other.author &&
          intro == other.intro &&
          kind == other.kind &&
          lastChapter == other.lastChapter &&
          updateTime == other.updateTime &&
          wordCount == other.wordCount &&
          nextPage == other.nextPage;
}

/// 4.4.4 TocRule (目录规则)
class TocRule {
  final String? preUpdateJs;
  final String? chapterList;
  final String? chapterName;
  final String? chapterUrl;
  final String? formatJs;
  final bool? isVolume;
  final bool? isVip;
  final bool? isPay;
  final String? updateTime;
  final String? nextTocUrl;

  const TocRule({
    this.preUpdateJs,
    this.chapterList,
    this.chapterName,
    this.chapterUrl,
    this.formatJs,
    this.isVolume,
    this.isVip,
    this.isPay,
    this.updateTime,
    this.nextTocUrl,
  });

  @override
  int get hashCode =>
      preUpdateJs.hashCode ^
      chapterList.hashCode ^
      chapterName.hashCode ^
      chapterUrl.hashCode ^
      formatJs.hashCode ^
      isVolume.hashCode ^
      isVip.hashCode ^
      isPay.hashCode ^
      updateTime.hashCode ^
      nextTocUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TocRule &&
          runtimeType == other.runtimeType &&
          preUpdateJs == other.preUpdateJs &&
          chapterList == other.chapterList &&
          chapterName == other.chapterName &&
          chapterUrl == other.chapterUrl &&
          formatJs == other.formatJs &&
          isVolume == other.isVolume &&
          isVip == other.isVip &&
          isPay == other.isPay &&
          updateTime == other.updateTime &&
          nextTocUrl == other.nextTocUrl;
}
