// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/book.dart';
import 'api/book_source.dart';
import 'api/data_base.dart';
import 'api/read_record.dart';
import 'api/web_book.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'models/book.dart';
import 'models/book_source.dart';
import 'models/chapter.dart';
import 'models/chapter_content.dart';
import 'models/read_record.dart';
import 'models/rules.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BookApiPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BookSourceApiPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ReadRecordApiPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WebBookApiPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BookApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    dynamic raw,
  );

  @protected
  BookSourceApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    dynamic raw,
  );

  @protected
  ReadRecordApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    dynamic raw,
  );

  @protected
  WebBookApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    dynamic raw,
  );

  @protected
  BookApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    dynamic raw,
  );

  @protected
  BookSourceApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    dynamic raw,
  );

  @protected
  ReadRecordApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    dynamic raw,
  );

  @protected
  WebBookApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    dynamic raw,
  );

  @protected
  BookApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    dynamic raw,
  );

  @protected
  BookSourceApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    dynamic raw,
  );

  @protected
  ReadRecordApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    dynamic raw,
  );

  @protected
  WebBookApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Book dco_decode_book(dynamic raw);

  @protected
  BookInfoRule dco_decode_book_info_rule(dynamic raw);

  @protected
  BookSource dco_decode_book_source(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Book dco_decode_box_autoadd_book(dynamic raw);

  @protected
  BookInfoRule dco_decode_box_autoadd_book_info_rule(dynamic raw);

  @protected
  BookSource dco_decode_box_autoadd_book_source(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ContentRule dco_decode_box_autoadd_content_rule(dynamic raw);

  @protected
  ExploreRule dco_decode_box_autoadd_explore_rule(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ReadRecord dco_decode_box_autoadd_read_record(dynamic raw);

  @protected
  ReviewRule dco_decode_box_autoadd_review_rule(dynamic raw);

  @protected
  SearchRule dco_decode_box_autoadd_search_rule(dynamic raw);

  @protected
  TocRule dco_decode_box_autoadd_toc_rule(dynamic raw);

  @protected
  Chapter dco_decode_chapter(dynamic raw);

  @protected
  ChapterContent dco_decode_chapter_content(dynamic raw);

  @protected
  ContentRule dco_decode_content_rule(dynamic raw);

  @protected
  ExploreRule dco_decode_explore_rule(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Book> dco_decode_list_book(dynamic raw);

  @protected
  List<BookSource> dco_decode_list_book_source(dynamic raw);

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReadRecord> dco_decode_list_read_record(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Book? dco_decode_opt_box_autoadd_book(dynamic raw);

  @protected
  BookInfoRule? dco_decode_opt_box_autoadd_book_info_rule(dynamic raw);

  @protected
  BookSource? dco_decode_opt_box_autoadd_book_source(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ContentRule? dco_decode_opt_box_autoadd_content_rule(dynamic raw);

  @protected
  ExploreRule? dco_decode_opt_box_autoadd_explore_rule(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ReadRecord? dco_decode_opt_box_autoadd_read_record(dynamic raw);

  @protected
  ReviewRule? dco_decode_opt_box_autoadd_review_rule(dynamic raw);

  @protected
  SearchRule? dco_decode_opt_box_autoadd_search_rule(dynamic raw);

  @protected
  TocRule? dco_decode_opt_box_autoadd_toc_rule(dynamic raw);

  @protected
  ReadRecord dco_decode_read_record(dynamic raw);

  @protected
  ReviewRule dco_decode_review_rule(dynamic raw);

  @protected
  SearchRule dco_decode_search_rule(dynamic raw);

  @protected
  TocRule dco_decode_toc_rule(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BookApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    SseDeserializer deserializer,
  );

  @protected
  BookSourceApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    SseDeserializer deserializer,
  );

  @protected
  ReadRecordApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    SseDeserializer deserializer,
  );

  @protected
  WebBookApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    SseDeserializer deserializer,
  );

  @protected
  BookApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    SseDeserializer deserializer,
  );

  @protected
  BookSourceApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    SseDeserializer deserializer,
  );

  @protected
  ReadRecordApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    SseDeserializer deserializer,
  );

  @protected
  WebBookApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    SseDeserializer deserializer,
  );

  @protected
  BookApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    SseDeserializer deserializer,
  );

  @protected
  BookSourceApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    SseDeserializer deserializer,
  );

  @protected
  ReadRecordApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    SseDeserializer deserializer,
  );

  @protected
  WebBookApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Book sse_decode_book(SseDeserializer deserializer);

  @protected
  BookInfoRule sse_decode_book_info_rule(SseDeserializer deserializer);

  @protected
  BookSource sse_decode_book_source(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Book sse_decode_box_autoadd_book(SseDeserializer deserializer);

  @protected
  BookInfoRule sse_decode_box_autoadd_book_info_rule(
    SseDeserializer deserializer,
  );

  @protected
  BookSource sse_decode_box_autoadd_book_source(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ContentRule sse_decode_box_autoadd_content_rule(SseDeserializer deserializer);

  @protected
  ExploreRule sse_decode_box_autoadd_explore_rule(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ReadRecord sse_decode_box_autoadd_read_record(SseDeserializer deserializer);

  @protected
  ReviewRule sse_decode_box_autoadd_review_rule(SseDeserializer deserializer);

  @protected
  SearchRule sse_decode_box_autoadd_search_rule(SseDeserializer deserializer);

  @protected
  TocRule sse_decode_box_autoadd_toc_rule(SseDeserializer deserializer);

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer);

  @protected
  ChapterContent sse_decode_chapter_content(SseDeserializer deserializer);

  @protected
  ContentRule sse_decode_content_rule(SseDeserializer deserializer);

  @protected
  ExploreRule sse_decode_explore_rule(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Book> sse_decode_list_book(SseDeserializer deserializer);

  @protected
  List<BookSource> sse_decode_list_book_source(SseDeserializer deserializer);

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReadRecord> sse_decode_list_read_record(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Book? sse_decode_opt_box_autoadd_book(SseDeserializer deserializer);

  @protected
  BookInfoRule? sse_decode_opt_box_autoadd_book_info_rule(
    SseDeserializer deserializer,
  );

  @protected
  BookSource? sse_decode_opt_box_autoadd_book_source(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ContentRule? sse_decode_opt_box_autoadd_content_rule(
    SseDeserializer deserializer,
  );

  @protected
  ExploreRule? sse_decode_opt_box_autoadd_explore_rule(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ReadRecord? sse_decode_opt_box_autoadd_read_record(
    SseDeserializer deserializer,
  );

  @protected
  ReviewRule? sse_decode_opt_box_autoadd_review_rule(
    SseDeserializer deserializer,
  );

  @protected
  SearchRule? sse_decode_opt_box_autoadd_search_rule(
    SseDeserializer deserializer,
  );

  @protected
  TocRule? sse_decode_opt_box_autoadd_toc_rule(SseDeserializer deserializer);

  @protected
  ReadRecord sse_decode_read_record(SseDeserializer deserializer);

  @protected
  ReviewRule sse_decode_review_rule(SseDeserializer deserializer);

  @protected
  SearchRule sse_decode_search_rule(SseDeserializer deserializer);

  @protected
  TocRule sse_decode_toc_rule(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    BookApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    BookSourceApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    ReadRecordApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    WebBookApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    BookApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    BookSourceApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    ReadRecordApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    WebBookApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    BookApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    BookSourceApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    ReadRecordApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    WebBookApi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_book_info_rule(BookInfoRule self, SseSerializer serializer);

  @protected
  void sse_encode_book_source(BookSource self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_info_rule(
    BookInfoRule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book_source(
    BookSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_content_rule(
    ContentRule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_explore_rule(
    ExploreRule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_read_record(
    ReadRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_review_rule(
    ReviewRule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_rule(
    SearchRule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_toc_rule(TocRule self, SseSerializer serializer);

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_content(
    ChapterContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content_rule(ContentRule self, SseSerializer serializer);

  @protected
  void sse_encode_explore_rule(ExploreRule self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book(List<Book> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_source(
    List<BookSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_read_record(
    List<ReadRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book(Book? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_info_rule(
    BookInfoRule? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_book_source(
    BookSource? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content_rule(
    ContentRule? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_explore_rule(
    ExploreRule? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_read_record(
    ReadRecord? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_review_rule(
    ReviewRule? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_search_rule(
    SearchRule? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_toc_rule(
    TocRule? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_read_record(ReadRecord self, SseSerializer serializer);

  @protected
  void sse_encode_review_rule(ReviewRule self, SseSerializer serializer);

  @protected
  void sse_encode_search_rule(SearchRule self, SseSerializer serializer);

  @protected
  void sse_encode_toc_rule(TocRule self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookApi(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookSourceApi(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReadRecordApi(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebBookApi(
    int ptr,
  );
}
