// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/book_source.dart';
import '../models/rules.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BookSourceApi>>
abstract class BookSourceApi implements RustOpaqueInterface {
  Future<void> deleteSource({required String url});

  Future<BookSource?> getSource({required String url});

  Future<List<BookSource>> importFromFile({required String filePath});

  Future<List<BookSource>> importFromText({required String text});

  Future<List<BookSource>> importFromUrl({required String url});

  Future<List<BookSource>> listAllSources();

  Future<List<BookSource>> listEnabledSources();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BookSourceApi> newInstance() =>
      RustLib.instance.api.crateApiBookSourceBookSourceApiNew();

  Future<void> updateSource({required BookSource source});
}
