// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/book.dart';
import '../models/chapter.dart';
import '../models/read_record.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BookApi>>
abstract class BookApi implements RustOpaqueInterface {
  Future<void> deleteBook({required String bookId});

  Future<Book?> getBook({required String bookId});

  Future<Book> importBook({required String filePath});

  Future<List<Book>> listBooks();

  Future<List<Chapter>> loadBookToc({required String bookId});

  /// 获取指定章节内容
  Future<String> loadChapterContent({
    required String bookId,
    required BigInt chapterIndex,
  });

  Future<ReadRecord?> loadReadProgress({required String bookId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BookApi> newInstance() =>
      RustLib.instance.api.crateApiBookBookApiNew();

  Future<void> updateReadProgress({required ReadRecord record});
}
