// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_db`

/// 初始化全局数据库连接池
/// 应在应用启动时调用一次
Future<void> initDatabase() =>
    RustLib.instance.api.crateApiDataBaseInitDatabase();

/// 检查数据库是否已初始化
Future<bool> isInitialized() =>
    RustLib.instance.api.crateApiDataBaseIsInitialized();
