// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/read_record.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReadRecordApi>>
abstract class ReadRecordApi implements RustOpaqueInterface {
  /// 创建阅读进度
  Future<void> createReadRecord({required ReadRecord record});

  /// 删除阅读进度
  Future<void> deleteReadRecord({required String bookId});

  /// 删除阅读记录
  Future<void> deleteRecordByBookId({required String bookId});

  /// 获取阅读进度
  Future<ReadRecord?> getReadRecord({required String bookId});

  /// 根据book_id获取阅读记录
  Future<ReadRecord?> getRecordByBookId({required String bookId});

  /// 按最后阅读时间倒序列出所有记录
  Future<List<ReadRecord>> listRecent();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ReadRecordApi> newInstance() =>
      RustLib.instance.api.crateApiReadRecordReadRecordApiNew();

  /// 更新阅读进度
  Future<void> updateReadRecord({required ReadRecord record});

  /// 根据book_id更新阅读记录
  Future<void> updateRecordByBookId({
    required String bookId,
    required ReadRecord record,
  });
}
