// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/book.dart';
import '../models/book_source.dart';
import '../models/chapter.dart';
import '../models/chapter_content.dart';
import '../models/read_record.dart';
import '../models/rules.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WebBookApi>>
abstract class WebBookApi implements RustOpaqueInterface {
  /// 添加网络书籍到书架（写入 books/chapters/read_records）
  ///
  /// - `book_url`: 书籍详情页 URL（也将作为网络书籍的 `book_id`）
  Future<Book> addNetworkBook({
    required BookSource bookSource,
    required String bookUrl,
  });

  Future<ReadRecord> createReadRecord({
    required String bookId,
    required PlatformInt64 chapterIndex,
    required PlatformInt64 chapterPos,
  });

  Future<Book> getBookInfo({
    required BookSource bookSource,
    required String bookUrl,
  });

  Future<Book> getBookInfoFromSearch({
    required BookSource bookSource,
    required String bookUrl,
    required Book baseBook,
  });

  Future<List<Chapter>> getBookToc({
    required BookSource bookSource,
    required String tocUrl,
  });

  Future<List<String>> getBookTocUrls({
    required BookSource bookSource,
    required String bookUrl,
  });

  Future<List<String>> getBookTocUrlsFromSearch({
    required BookSource bookSource,
    required String bookUrl,
    required Book baseBook,
  });

  Future<ChapterContent> getChapterContent({
    required String bookId,
    required BookSource bookSource,
    required String chapterUrl,
  });

  Future<List<BookSource>> loadBookSources();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WebBookApi> newInstance() =>
      RustLib.instance.api.crateApiWebBookWebBookApiNew();

  Future<List<Book>> search({required String keyword});
}
